# Generated by Django 2.2.7 on 2022-05-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_auto_20220514_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
