# Generated by Django 2.2.7 on 2022-05-19 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_auto_20220519_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='testavatar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/avatars'),
        ),
        migrations.AlterField(
            model_name='testavatar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
