# Generated by Django 2.2.7 on 2022-05-19 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quiz', '0011_auto_20220519_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='name',
        ),
        migrations.AddField(
            model_name='avatar',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.Marks_Of_User'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/avatars'),
        ),
        migrations.DeleteModel(
            name='testAvatar',
        ),
    ]
