# Generated by Django 2.2.7 on 2022-05-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_remove_avatar_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, default='static/avatars/bee_qCPs9vg.png', null=True, upload_to='static/avatars'),
        ),
    ]
