# Generated by Django 2.2.7 on 2022-05-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0016_auto_20220519_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, default='whale_upZBjHq.png', null=True, upload_to='static/avatars'),
        ),
    ]
